es/urls.py
from django.urls import path, re_path

from public.acerade import acercade
from public.view_changepass import changepass

#from .view_pago import pagoView
from public.view_registro import registerView
from public.view_restaurar import restaurar
from public.view_recordarusername import recordarusername
from public.view_perfil import perfil

from .view_login import login_tienda, logout_tienda
from .view_conferences import conferences
from .view_members import members
from .index import indexEs

urlpatterns = [
    # path('', index),
    path('', indexEs),
    path('members/', members),
path('previous-events/', conferences),
    re_path(r'^acercade/', acercade),
    #path('pago/<str:pedido_id>/', pagoView),
    re_path(r'^perfil/', perfil),
    # url(r'^register/', registro),
    re_path(r'^login/', login_tienda),
    re_path(r'^logout/', logout_tienda),
    re_path(r'^restorepass/', restaurar),
    re_path(r'^restoreusername/', recordarusername),
    re_path(r'^changepass/', changepass),
    re_path(r'^register/', registerView),

]

pedidos/urls.py
from django.urls import re_path
from pedidos.view_pedido import pedidoView

pedidos_urls = (

    {
        "nombre": "Solicitudes de registro",
        "url": 'solicitudes-registro/',
        "vista": pedidoView,
    },
)

urlpatterns = [

]

for u in pedidos_urls:
    urlpatterns.append(re_path(r'^{}$'.format(u["url"]), u["vista"]))

pryiberoamericano/urls.py
"""
   Django 4.1
"""
from django.contrib import admin
from django.urls import path

from area_geografica.urls import area_geografica_urls
from core.funciones import db_table_exists
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import set_language
from django.views.generic import RedirectView
from django.views.static import serve

from autenticacion.urls import autenticacion_urls
from autenticacion.view_perfil import perfilView
from core.ajax import ConsultasAjax
from financiero.urls import financiero_urls
from landing.urls import landing_urls
from pedidos.urls import pedidos_urls
from pryiberoamericano.view_clearsitedata import clearSiteDataView
from pryiberoamericano import settings
from pryiberoamericano.view_redirect import redirectView, redirectToUrlView
from public.check_language import check_language
from seguridad.models import Configuracion, Modulo
from seguridad.urls import seguridad_urls
from seguridad.view_index import index
from django.conf.urls.static import static
from core.consultas import consultas


confi = Configuracion.get_instancia()
icon_url = confi.ico.url if confi.ico else ""
favicon_view = RedirectView.as_view(url=icon_url, permanent=True)
urls_sistema = (
    {
        "nombre": "Áreas Geográficas",
        "url": "area-geografica/",
        "sub_urls": area_geografica_urls,
        "include": include('area_geografica.urls'),
        "name": None,
        "vista": None
    },
    {
        "nombre": "Autenticación",
        "url": 'autenticacion/',
        "sub_urls": autenticacion_urls,
        "include": include('autenticacion.urls'),
        "name": None,
        "vista": None
    },
    {
        "nombre": "Seguridad",
        "url": 'seguridad/',
        "sub_urls": seguridad_urls,
        "include": include('seguridad.urls'),
        "name": None,
        "vista": None
    },
    {
        "nombre": "Landing",
        "url": 'landing/',
        "sub_urls": landing_urls,
        "include": include('landing.urls'),
        "name": None,
        "vista": None
    },
    {
        "nombre": "Financiero",
        "url": "financiero/",
        "sub_urls": financiero_urls,
        "include": include('financiero.urls'),
        "name": None,
        "vista": None
    },
    {
        "nombre": "Pedidos",
        "url": "pedidos/",
        "sub_urls": pedidos_urls,
        "include": include('pedidos.urls'),
        "name": None,
        "vista": None
    },
)
urlpatterns = [
    path('set-language/', set_language, name='set_language'),
    path('check-language/', check_language, name='check_language'),
    path('panel/', index),
    path('admin/', admin.site.urls),
]
urlpatterns += i18n_patterns (

    path('perfilpanel/', perfilView),
    path('consultas/', consultas, name='Consultas API'),
    path('ajaxrequest/', ConsultasAjax.as_view(), name='Ajax Consultas v1'),
    path('ajaxrequest/<slug:accion>', ConsultasAjax.as_view(), name='Ajax Consultas v1'),
    path('ajaxrequest/<slug:accion>/<str:pk>', ConsultasAjax.as_view(), name='Ajax Consultas v1'),
    path('redirect-to-url/<int:pk>/', redirectToUrlView),
    # urls apache
    re_path(r'^favicon\.ico', favicon_view),
    path('clear-site-data/', clearSiteDataView),
    # select2
    path("select2/", include("django_select2.urls")),
    path('', include('public.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
                    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), ]

for u in urls_sistema:
    if u["vista"] and not u["include"]:
        if u["name"]:
            urlpatterns.append(path('{}'.format(u["url"]), u["vista"], name=u["name"]))
        else:
            urlpatterns.append(path('{}'.format(u["url"]), u["vista"]))
    elif not u["vista"] and u["include"]:
        if u["name"]:
            urlpatterns.append(path('{}'.format(u["url"]), u["include"], name=u["name"]))
        else:
            urlpatterns.append(path('{}'.format(u["url"]), u["include"]))

if db_table_exists(Modulo._meta.db_table):
    qs_modulos = Modulo.objects.filter(status=True)
    for u in urls_sistema:
        url = "/{}".format(u["url"])
        modulos = qs_modulos.filter(url__startswith=url)
        if u["sub_urls"]:
            for su in u["sub_urls"]:
                mod_url = "/{}{}".format(u["url"], su["url"])
                if modulos.filter(url=mod_url).exists():
                    mod = modulos.filter(url=mod_url).first()
                    if mod.nombre != su["nombre"]:
                        mod.nombre = su["nombre"]
                        mod.save()

admin.site.site_header = "{} {}".format("Administración", "pryiberoamericano")
admin.site.site_title = "{} {}".format("Administración", "pryiberoamericano")

pedidos/models.py
from decimal import Decimal

from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.contenttypes.models import ContentType
from core.custom_models import ModeloBase
from core.funciones_adicionales import customgetattr
from core.models_utils import UserUploadToPath
from core.validadores import validate_file_size_3mb, validate_file_size_20mb
from pryiberoamericano.settings import AUTH_USER_MODEL


def funcUser(instance):
    return instance.user

def _estado_pedido(self):
    s = ""
    if self.estado == "PENDIENTE":
        s = '<i class="text-info fas fa-ellipsis-h"></i> Pendiente de validar'
    elif self.estado == "EN_ESPERA":
        s = '<i class="text-warning far fa-clock"></i> Pendiente de aprobación'
    elif self.estado == "ANULADO":
        s = '<i class="text-danger fas fa-times-circle"></i> Anulado'
    elif self.estado == "DEVUELTO":
        s = '<i class="text-danger fas fa-times-circle"></i> Devuelto'
    elif self.estado == "COMPLETADO":
        s = '{} Completado'.format('<i class="text-success fas fa-check-circle"></i>')
    elif self.estado == "ERROR_METODO_PAGO":
        s = '{} Error en el pago'.format('<i class="text-danger fas fa-times-circle"></i>')
    return mark_safe(s)


METODO_PAGOS = (
    ("PAYPAL", "Paypal"),
    ("TRANSFERENCIA_BANCARIA", "Transferencia Bancaria")
)


ESTADO_PEDIDO = (
    ("PENDIENTE", "Pendiente de validar"),
    ("EN_ESPERA", "En espera de aprobación"),
    ("ANULADO", "Anulado"),
    ("COMPLETADO", "Completado"),
    ("DEVUELTO", "Devuelto",),
    ("ERROR_METODO_PAGO", "Error en el médoto de pago")
)


TIPO_ENTORNO = ((True, "Producción"), (False, "Test"),)


class Pedido(ModeloBase):
    ip = models.CharField(max_length=1000, blank=True, null=True, verbose_name='Ip')
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.PROTECT, verbose_name="Usuario que hizo el pedido", related_name='+')
    cuota = models.ForeignKey("landing.ConferenceFee", on_delete=models.PROTECT, verbose_name="Cuota")
    archivo_evidencia = models.FileField(upload_to=UserUploadToPath("pedidos/archives/", funcUser), null=True, blank=True)
    special_price_student = models.BooleanField("Precio especial para estudiantes", default=False)
    observacion = models.TextField("Notas de pedido", null=True, blank=True, default='')
    metodo_pago = models.CharField("Método de pago", max_length=255, choices=METODO_PAGOS)
    subtotal = models.DecimalField(verbose_name="Subtotal", default=0, max_digits=30, decimal_places=2, )
    impuestos = models.DecimalField(verbose_name="impuestos", default=0, max_digits=30, decimal_places=2, )
    total = models.DecimalField(verbose_name="Total", default=0, max_digits=30, decimal_places=2, )
    # DATOS TRANSFERENCIA
    comprobante = models.CharField("Comprobante", max_length=500, null=True, blank=True)
    comprobantejson = models.TextField("Comprobante Json", null=True, blank=True)
    entidad_fin = models.ForeignKey("financiero.CuentaFinancieraEmpresa", on_delete=models.PROTECT, null=True, blank=True)
    archivo_pago = models.FileField(upload_to=UserUploadToPath("pedidos/pagos/", funcUser), validators=[FileExtensionValidator(['jpg', 'jpeg', 'png', 'tiff', "jfif", "pdf"]), validate_file_size_3mb], null=True, blank=True)
    estado = models.CharField("Estado", max_length=255, choices=ESTADO_PEDIDO)
    fecha_expira = models.DateTimeField("Fecha que expira el pedido. Si no lo completa, se borrará en la fecha establecida.", blank=True, null=True)
    session_user = models.ForeignKey("seguridad.SessionUser", on_delete=models.PROTECT, null=True, blank=True)
    pago_reversado = models.BooleanField("Pago reversado", default=False)
    fecha_reversado = models.DateTimeField("Fecha de pago reversado", null=True, blank=True)
    razon_reverso = models.TextField(default='', blank=True, null=True)
    pago_reversado_por = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.PROTECT, verbose_name="Pago reversado por", null=True, blank=True, related_name="venta_pedido_pago_reversado_por")
    modo_pago = models.BooleanField("Ejecución de Paypal", choices=TIPO_ENTORNO, default=1)

    def get_papers(self):
        return self.papersauthorpedido_set.filter(status=True)

    def get_student(self):
        return 'text-success fa fa-check-circle' if self.special_price_student else 'text-danger fa fa-times-circle'

    def get_telefono(self):
        return self.user.telefono_formateado()

    def get_nombres(self):
        return self.user.datos()

    def __str__(self):
        return f"{self.id} - {self.user.username} Sub: {self.subtotal}, Imp: {self.impuestos}, Total: {self.total}, Estado: {self.get_estado_display()}"

    @property
    def es_pago_electronico(self):
        return self.metodo_pago in ("PAYPHONE", "PAYPAL")

    def typefile(self):
        if self.archivo_pago:
            return self.archivo_pago.name[self.archivo_pago.name.rfind("."):]
        else:
            return None

    def get_icon(self):
        i = ''
        if self.metodo_pago == "PAYPAL":
            i = '<b><i class="fab fa-paypal" style="color: #2E86C1;"></i></b>'
        elif self.metodo_pago == "TRANSFERENCIA_BANCARIA":
            i = '<i class="fas fa-comments-dollar"></i>'
        return mark_safe(i)

    def estado_pedido(self):
        return _estado_pedido(self)

    def lista_histial(self):
        return HistorialPedido.objects.filter(status=True, pedido__id=self.pk).order_by('-id')

    def get_resp_metodo_pago(self):
        Modelo = PagoTransferencia if self.metodo_pago == "TRANSFERENCIA_BANCARIA" else \
                 PagoPayPal if self.metodo_pago == "PAYPAL" else None

        obj = Modelo.objects.filter(
            content_type__id=ContentType.objects.get_for_model(self).id,
            object_id=self.id
        ).first() if Modelo else None

        salida = []

        if obj:
            for x in obj._meta.fields:
                f = x.name
                if not f in ('id', 'status', 'fecha_registro', 'hora_registro', 'content_type', 'object_id', 'modelo', 'paypal_fee', 'final_capture', 'usuario_creacion'):
                    salida.append(
                        {
                            "nombre": obj._meta.get_field(f).verbose_name,
                            "valor": customgetattr(obj, f)
                        }
                    )

        return salida

    class Meta:
        ordering = ("estado", "id")
        verbose_name = "Pedido"
        verbose_name_plural = "Pedidos"
        # constraints = [
        #     models.CheckConstraint(check=Q(metodo_pago__in=("PAYPHONE", "TRANSFERENCIA_BANCARIA", "PAYPAL")),
        #                            name='venta__Pedido__metodo_pago__in'),
        #     models.CheckConstraint(check=Q(estado__in=list(x[0] for x in ESTADO_PEDIDO)),
        #                            name='venta__Pedido__estado__in'),
        # ]


class PagoTransferencia(ModeloBase):
    # GenericForeignKey
    content_type = models.ForeignKey("contenttypes.ContentType", on_delete=models.PROTECT, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    modelo = GenericForeignKey('content_type', 'object_id')
    # ----------------------------------------------------------------
    infobanco = models.CharField("Información Bancaria", max_length=1000)
    infopersona = models.CharField("Información del Dueño de la cueta", max_length=1000)

    def __str__(self):
        return "{}, {}".format(self.infobanco, self.infopersona)


class PagoPayPal(ModeloBase):
    # GenericForeignKey
    content_type = models.ForeignKey("contenttypes.ContentType", on_delete=models.PROTECT, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    modelo = GenericForeignKey('content_type', 'object_id')
    # ----------------------------------------------------------------
    transactionId = models.CharField("transactionId", max_length=255, null=True, blank=True)
    transaction_status = models.CharField("Transaction Status", max_length=255, null=True, blank=True)
    currency_code = models.CharField("currency_code", max_length=20, null=True, blank=True)
    subtotal = models.DecimalField("subtotal", max_digits=19, decimal_places=2)
    shipping = models.DecimalField("shipping", max_digits=19, decimal_places=2)
    total = models.DecimalField("total", max_digits=19, decimal_places=2)
    paypal_fee = models.DecimalField("paypal_fee", max_digits=19, decimal_places=2, default=0)
    tiendaemail = models.CharField("tiendaemail", max_length=255, null=True, blank=True)
    tiendaid = models.CharField("tiendaid", max_length=255, null=True, blank=True)
    soft_descriptor = models.CharField("soft_descriptor", max_length=255, null=True, blank=True)
    clientenombres = models.CharField("clientenombres", max_length=255, null=True, blank=True)
    clienteemail = models.CharField("clienteemail", max_length=255, null=True, blank=True)
    clienteid = models.CharField("clienteid", max_length=255, null=True, blank=True)
    clientecountry_code = models.CharField("clientecountry_code", max_length=255, null=True, blank=True)
    final_capture = models.BooleanField("final_capture", null=True, blank=True)
    capture_id = models.TextField(null=True, blank=True, verbose_name="Capture ID")
    order_id = models.CharField("order_id", max_length=255, null=True, blank=True)
    authorization_id = models.CharField("authorization_id", max_length=255, null=True, blank=True)
    datajson = models.TextField("Respuesta Api")

    def __str__(self):
        return self.datajson

    @staticmethod
    def registrar(modelo, data, order_id, auth_id, capture_id):
        import json
        from core.funciones import round_num_dec

        obj = None

        try:

pedidos/views.py
from django.shortcuts import render

# Create your views here.

templates/pedidos/pedido/modaldetalle.html
{% load humanize %}
{% load templatefunctions %}
<style>
    .text{
        font-size: 14px;
    }
</style>
<div class="row">
    <div class="col-lg-12">
        <div class="d-sm-flex align-items-center justify-content-between py-1">
            <div class="me-auto">
                <h4 class="h4 mb-1">
                    {{ detalle.item.nombre }}
                </h4>
            </div>
            <div class="text-right">
                <div class="fs-5 mb-1 pr-5"><b>$ {{ detalle.precio|intcomma }}</b></div>
            </div>
        </div>

        <ul class="list-unstyled py-3 mb-0">
            <li class="d-flex justify-content-between mb-2">
                <span class="text">Subtotal:</span> <span class="fw-semibold ms-2 pr-5"><b>$ {{ pedido.subtotal|intcomma }}</b></span>
            </li>
            {% if pedido.impuestos %}
                <li class="d-flex justify-content-between mb-2">
                    <span class="text" >(+) Impuestos:</span> <span
                        class="fw-semibold ms-2 impuesto_ pr-5"><b>$ {{ pedido.impuestos|intcomma }}</b></span>
                </li>
            {% endif %}
        </ul>
        <div class="d-flex align-items-center justify-content-between border-top fs-xl pt-4">
            <span class="text" > Total:</span><span
                class="fs-3 fw-semibold text-dark ms-2 total_ pr-5"><b>$ {{ pedido.total|intcomma }}</b></span>
        </div>
        <div class="d-flex align-items-center justify-content-end fs-xl pt-4">
            <span class="pr-5">{{ pedido.get_metodo_pago_display }}</span>
        </div>
    </div>
</div>

templates/pedidos/pedido/pago_pendiente.html
{% extends 'base.html' %}
{% load humanize %}
{% load templatefunctions %}
{% block atras %}{{ request.path }}{% endblock %}
{% block head %}
    <link rel="stylesheet" href="/static/fancybox/css/core.css"/>
{% endblock %}
{% block content %}

    <div class="panel panel-inverse" data-sortable-id="form-stuff-2">

        <div class="panel-heading ui-sortable-handle">
            <h4 class="panel-title">{{ titulo }} Formulario</h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i
                        class="fa fa-expand"></i></a>
            </div>
        </div>


        <div class="panel-body">
            <div class='row'>
                <div class="col-lg-6">
                    <span class="pull-right hidden-print">
                            {% if compra.user.telefono %}
                                <a class="btn btn-success"
                                   onclick="contactarcliente('{{ compra.get_telefono }}', '{{ compra.get_nombres }}')"
                                   href="javascript:void(0);">
                                <i class="fa fa-whatsapp"></i> Contactar Cliente
                            </a>
                            {% endif %}
                    </span>
                    <span>
                            <h3><i class="fa fa-money-bill"></i> Detalle del Pago</h3>
                        </span>
                    <hr>
                    <div class="form-group">
                        <h5 class="h5">Comprobante</h5>
                        <div>
                            <input data-show-remove="false" class="form-control" type="file"
                                   id="id_archivo_pago" data-max-file-size="3M"
                                   data-default-file="{{ obj.archivo_pago.url }}"
                                   data-allowed-file-extensions="jpg jpeg png tiff jfif pdf">
                            {% with urlarchivo='https://docs.google.com/gview?url='|add:URL_GENERAL|add:obj.archivo_pago.url|add:'&embedded=true' %}
                                <a {% if obj.archivo_pago_is_image %}data-fancybox="image"
                                   href="{{ obj.archivo_pago.url }}" {% else %} data-fancybox
                                   data-type="iframe"
                                   href="{{ urlarchivo }}" {% endif %} class="btn btn-link px-0">
                                    Ver comprobante en otra ventana
                                </a>
                            {% endwith %}
                            o
                            <a class="btn btn-link pl-0"
                               href="{{ obj.archivo_pago.url }}" target="_blank">
                                Descargar
                            </a>
                        </div>
                    </div>
                    {% with resp_metodo_pago=compra.get_resp_metodo_pago %}
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped">
                                <thead class="thead-light">
                                <tr>
                                    <th colspan="2">
                                        <h3 class="modal-title">{{ compra.get_icon }} Pago
                                            por {{ compra.get_metodo_pago_display }}</h3>
                                    </th>
                                </tr>
                                </thead>
{#                                <tbody>#}
{#                                <tr>#}
{#                                    <th class="text-left">IP</th>#}
{#                                    <td class="text-left">{{ compra.session_user.ip }}</td>#}
{#                                </tr>#}
{#                                <tr>#}
{#                                    <th class="text-left">Dispositivo</th>#}
{#                                    <td class="text-left">{{ compra.session_user.dispositivo }}</td>#}
{#                                </tr>#}
{#                                <tr>#}
{#                                    <th class="text-left">Localidad</th>#}
{#                                    <td class="text-left">{{ compra.session_user.areageografica }}</td>#}
{#                                </tr>#}
                                {% for r in resp_metodo_pago %}
                                    <tr>
                                        <th class="text-left">{{ r.nombre }}</th>
                                        <td class="text-left">{{ r.valor }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% endwith %}
                </div>
                <div class="col-lg-6">
                    <form method="post" enctype="multipart/form-data" action="{{ ruta }}"
                          class="form-horizontal form-label-left">
                        {% csrf_token %}
                        <input type="hidden" name="pk" value="{{ pk|default:0 }}"/>
                        <input type="hidden" name="action" value="{{ action }}"/>
                        <fieldset>
                            <span>
                                <h3><i class="fa fa-search"></i> Validación</h3>
                            </span>
                            <hr>
                            <div class="row">
                                <div class="col-lg-12">
                                    <table class="table table-bordered">
                                        <tbody>
                                        <tr>
                                            <td>Cliente</td>
                                            <td>{{ obj.user.username }} - {{ obj.user.get_full_name }}
                                                - {{ obj.user.documento|default:'' }}</td>
                                        </tr>
                                        <tr>
                                            <td>Email</td>
                                            <td>{{ obj.user.email }}</td>
                                        </tr>
                                        <tr>
                                            <td>Cuenta</td>
                                            <td>
                                                {% if obj.entidad_fin %}
                                                    {{ obj.entidad_fin.num_cuenta }} -
                                                    {{ obj.entidad_fin.ent_fin.nombre }}
                                                {% else %}
                                                    Ninguna
                                                {% endif %}</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <table class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th>Item</th>
                                            <th class="text-center" width="10%">Precio</th>
                                            {#                                    <th class="text-right" width="20%">SUBTOTAL</th>#}
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for l in detallepedido %}
                                            <tr>
                                                <td>
                                                    <span class="text-inverse">{{ l.item.nombre }}</span>
                                                </td>
                                                <td style="vertical-align : middle" class="text-center">
                                                    {{ SIMBOLO_MONEDA }}{{ l.precio|intcomma }}
                                                </td>
                                                {#                                        <td style="vertical-align : middle" class="text-right">#}
                                                {#                                            {{ SIMBOLO_MONEDA }}{{ l.total|intcomma }}</td>#}
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset>
                            <span>
                                <h3><i class="fa fa-check-double"></i> Respuesta</h3>
                            </span>
                            <hr>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <h5 class="h5">Estado de la transacción</h5>
                                        <select required="" class="form-control" name="estado" id="id_estado">
                                            <option value="COMPLETADO">
                                                Aprobar
                                            </option>
                                            <option value="ANULADO">
                                                Rechazar
                                            </option>
                                        </select>
                                        <div class="invalid-feedback" id="errorMessageestado"></div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <h5 class="h5">Observación</h5>
                                        <textarea placeholder="Sea claro y específico" rows="4" required=""
                                                  class="form-control"
                                                  id="id_observacion"
                                                  name="observacion"></textarea>
                                        <div class="invalid-feedback" id="errorMessageobservacion"></div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <div class="form-group">
                            <a class="btn btn-danger" style="color: #ffffff;" href="{{ ruta }}">
                                <i class="fa fa-window-close"></i> Cancelar
                            </a>
                            <button {% if action != 'ver' %}type="submit" id="submit"{% else %}disabled{% endif %}
                                    class="btn btn-success">
                                <i class="fa fa-save"></i> Guardar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

{% block jscript %}
    <link rel="stylesheet" href="/static/fancybox/css/core.css"/>
    <script src="/static/fancybox/js/core.js"></script>
    <script src="/static/js/forms.js?version=11"></script>
    {% verbatim %}
    <script>
        var imagen1 = $('#id_archivo_pago').dropify({
            messages: {
                default: 'Arrastre y suelte el archivo del depósito o haga clic aquí.',
                replace: 'Arrastre y suelte el archivo del depósito o haga clic aquí.',
                remove: 'Eliminar',
                error: 'Ocurrió un error!'
            },
            error: {
                fileSize: "El tamaño del archivo debe ser máximo ({{ value }}).",
                fileExtension: "Sólo puede subir los archivos con las extensiones ({{ value }})."
            },
            imgFileExtensions: ["jpg", "jpeg", "png", "tiff", "jfif"]
        });
    </script>
    {% endverbatim %}
{% endblock %}